version: '3'

services:
  couchdb:
    image: apache/couchdb
    volumes: 
      - couchdb_data:/opt/couchdb/data apache/couchdb
    restart: always

  syncserver:
    image: lukasstruppek/syncserver
    command: >
      bash -c " sleep 10; "
    depends_on: 
      - couchdb
    ports:
      - "8443:8443"
    restart: always

volumes:
  couchdb_data: